Test coverage for methods from stub branch
tari-project/validator-node pull request #16
Opened 2020-05-26 21:52 UTC by Timo614

## Description
We merged in the stubs branch for consensus. This branch just adds a few tests I meant to add at the time but it ran into the weekend.

I noticed I made a mistake while rebasing prior to the consensus merge in that I disabled the consensus worker as part of that rebase. I fixed that here in this branch reintroducing the worker background logic in the server.rs file. 

## Motivation and Context
Fixed a few bugs as a result of the tests finding SQL problems on a path I can't hit yet but had stubs in place for.

## How Has This Been Tested?
This is mostly new tests.

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [x] New Tests
* [ ] Documentation

## Checklist:

* [x] I'm merging against the `development` branch.
* [x] I ran `cargo-fmt --all` before pushing.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.

2020-05-27 10:54 UTC, dunnock requested changes
This is great, I've left few suggestions which IMHO would help us in the future

2020-05-27 10:54 UTC, dunnock commented on node/src/api/server.rs
> +    actix_rt::spawn(async move {
Leaving note for the future
```suggestion
    // TODO: spawn consensus processors in separate Runtime
    actix_rt::spawn(async move {
```

2020-05-27 10:54 UTC, dunnock commented on node/src/api/server.rs
> +    let (consensus_sender, consensus_receiver) = mpsc::channel::<()>();
let's make more meaningful name to this signal, like kill_sender, kill_receiver etc?

2020-05-27 10:54 UTC, dunnock commented on node/src/consensus/consensus_worker.rs
> +                .expect("Validator node unable to load db client");
That's a good idea indeed, would be even better if you move it level higher so that work is blocked until db_client connection is established so we don't get a stack of tasks waiting on db (slow db, hanging db etc). Though that would require to make work function async, I don't see a problem with that as host function is async too.

2020-05-27 15:54 UTC, Timo614 commented on node/src/consensus/consensus_worker.rs
> +                .expect("Validator node unable to load db client");
Sounds good, moved it up a bit and am blocking on that call now as part of the work loop so should be good now / won't end up with all those tasks waiting on the db.

2020-05-27 15:55 UTC, Timo614 commented on node/src/api/server.rs
> +    actix_rt::spawn(async move {
Added it above

2020-05-27 15:57 UTC, Timo614 commented on node/src/db/models/asset_states.rs
> +            .execute(&stmt, &[&self.id, &self.blocked_until, &block_until])
Passing in the blocked until from the host to avoid issues with db time being out of sync.

2020-05-28 10:52 UTC, dunnock approved these changes

2020-05-28 10:53 UTC, dunnock commented
Cool, LGTM!

2020-05-28 13:12 UTC, merged