Auth middleware
tari-project/validator-node pull request #3
Opened 2020-05-08 21:34 UTC by Timo614

## Description
Adds basic middleware for parsing a signed JWT to verify user identity. The logic does this in two steps: 1) it parses the JWT and fetches the sub row which contains the user's public key in pem format 2) it uses the public key from the sub to verify the token was signed correctly

We could at this point do some basic checks but I think it may make sense to layer our authentication as Maxim suggested. 

Layers we'll need to cover:
- Create / migrate asset instructions will need to confirm the user has access currently granted for API access
- Asset and token level instructions will need to confirm the user either is the asset issuer or is included in the authorized_signers list for the given asset being modified

## Motivation and Context
This change adds the initial logic to parse out the user's public key. Without this we are unable to verify the user is who they claim to be for the purposes of performing actions via the API. This is in place of any sort of login system.

## How Has This Been Tested?
I've added a test for the from_request method of the access token extractor but I did some initial testing by adding a new endpoint temporarily to the routes: 

```
.service(
    web::resource("/test")
        .to(|access_token: AccessToken| HttpResponse::Ok().body(format!("{:?}", access_token))),
)
```

With this I confirmed that the access token was properly decoded / verified:
```
curl 'http://127.0.0.1:3001/test' 
{"error":"Unauthorized"}
2020-05-08 17:30:49.091485000 [tari_validator_node::api::errors::api_error] ERROR AuthError(AuthError { reason: "Missing auth token", error_type: Unauthorized })
```

```
curl 'http://127.0.0.1:3001/test' --header "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJzdWIiOiItLS0tLUJFR0lOIFJTQSBQVUJMSUMgS0VZLS0tLS1cbk1JSUNDZ0tDQWdFQXMzMzNMRWQwYUozNEl6RnN0UFBKRHJnc21EV04zZUVXRTJKcThsMDFDRk1Wbk9WTDhTWmhcbnlYdzNqS3ljbU5iakM4aWhHSVJzNUlSVUVtVXhGVnFXbDgvb05Ed00xU1NOYjR3TmJBSVdTSTRJRDI3bTl1blBcbm9LRmduRFEzUndzOG9INlNnRzdHMFhZeWptTWFSVlV2M1Z2d2Z0d2JiWWpDbmxpcjdvYlN0ZGZ2dlNibnZhb21cbnBxcERzTGYrd2lhUFRxREYwUTFVTEZXM3ZiMjcvQVZmUkhVekNTUVlxbjdZWkFhRUVsOU9TUnZJS292a0RmOVJcbjBaM28xbndZcHlnTEF3NVYvNG1lVGRBcGN1UXV0TFNKK0pXZ0xvNmlERlpvbngvVDdpNHU3QkZIVDZaQ0VibzdcbjI3K20rVzVETjdiZzlJN3J5aEpxOTcvSnltVkUrS0luU3RZYkh6YVZ0ZFNkYzdxSURxWFpPcmMzMVlYZ0diTXpcbmozVkRIMFNIT3hDM21YSmh1bFVNeVFSRGx2R1BLdWR0RldJNEZkRVVJZ1E1Sm95VjRKZS9PS3VYVmphdlkrQXpcbkZIOVJLKy9KcU1CSGQ1b01xMzh2TDJzYTRtNTJSaEFOTk5ENWpQME1HNmh6TGlBOVF2QllSbm5FMlAxRnlRZ1FcbjB1R1BhdmJoZk13S1NWMTZjM2g4MXU4djhaQjU4TUNjcTMwSW9oRlBHWUNzZWJ5dS93VWg4cjAwckhzaWl6RFJcbmxoZFo1VWw2NFB6TTVTODlIc1FYbnJycTRsS3ZpM1J0M3VBTVlSQ25rOThKWUpBc0UrVlBLaU9MSDJvUWdzUHFcbnhid1B0OFJEMnhuWUxyT3pvR2JaSXQwUVpiZnNmdWs1aGpQZ2o3R1FrRG5TclJOdFBZVmRvb0VDQXdFQUFRPT1cbi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS1cbiIsImlzcyI6InRhcmkiLCJleHAiOjE1ODkzMjc2MzQsImlzc3VlZCI6MTU4ODk2NzYzNH0.JjbuXgqNkhK3awW9awAQ9Nsuzuj7rW49Yfn0GHBbRVQ9Ay6rNXS5D4F-SOwWt6_4SvicBPMHLd6jWVlZ7zwPj0IWGmziobISRHcOWlqgJ00NB2yfy7ug-PPr1tBZDbMJQ2qO4iZ03OUFXMO2X0mM__pqf9BifMIAX0ImwG_XAuow7iimN02pc_pjvkJn8fh-s7hORSDjBFYjwMSvE0rPJicnk7YDd95V9HE_UAHZZqOUIpEdd6rx88WcmSmXB0Wud5NXovod41LsjdQyC5k1BjgLiHbgsHmiFMdONnirR80KB78nYZHam1b164aGQHVJtTobnbvK-B84s-3DQ5jqSAgZgvOTA992fGKEWH56NCZ5ILgWAmUnL2iMYVlk065I8vM-z9od90e5qZpI-nfoUq_bBZ3wVonZMxI8nIdUJV4PE5bfpbpMR4hSTpI4DMjW8cYX8qfYcgzyLl4mBpqkRF8_wxb5pXTw-XyLUqkYLkdWI_OfxrgQNgiAChac4AUar-kOp1W7CaVnV_kK-b9dF7sRUvLu0HNA_oVJ6MPqr3hMuPJk4PVewXhE23UF9wrXny9zzFuC6_SB-x5UsBZntgpr1f7hk-wotTr3mswz6YpoZoIfDF-qsjkwW6ZS3rI8XAfmZ_YqeEJUJPbn-nLmjwZk2i8emEh_AQcHGeCUsq0"
AccessToken { sub: "-----BEGIN RSA PUBLIC KEY-----\nMIICCgKCAgEAs333LEd0aJ34IzFstPPJDrgsmDWN3eEWE2Jq8l01CFMVnOVL8SZh\nyXw3jKycmNbjC8ihGIRs5IRUEmUxFVqWl8/oNDwM1SSNb4wNbAIWSI4ID27m9unP\noKFgnDQ3Rws8oH6SgG7G0XYyjmMaRVUv3VvwftwbbYjCnlir7obStdfvvSbnvaom\npqpDsLf+wiaPTqDF0Q1ULFW3vb27/AVfRHUzCSQYqn7YZAaEEl9OSRvIKovkDf9R\n0Z3o1nwYpygLAw5V/4meTdApcuQutLSJ+JWgLo6iDFZonx/T7i4u7BFHT6ZCEbo7\n27+m+W5DN7bg9I7ryhJq97/JymVE+KInStYbHzaVtdSdc7qIDqXZOrc31YXgGbMz\nj3VDH0SHOxC3mXJhulUMyQRDlvGPKudtFWI4FdEUIgQ5JoyV4Je/OKuXVjavY+Az\nFH9RK+/JqMBHd5oMq38vL2sa4m52RhANNND5jP0MG6hzLiA9QvBYRnnE2P1FyQgQ\n0uGPavbhfMwKSV16c3h81u8v8ZB58MCcq30IohFPGYCsebyu/wUh8r00rHsiizDR\nlhdZ5Ul64PzM5S89HsQXnrrq4lKvi3Rt3uAMYRCnk98JYJAsE+VPKiOLH2oQgsPq\nxbwPt8RD2xnYLrOzoGbZIt0QZbfsfuk5hjPgj7GQkDnSrRNtPYVdooECAwEAAQ==\n-----END RSA PUBLIC KEY-----\n", iss: "tari", exp: 1589327634, issued: 1588967634 }
```

Switching the route to:
```
    .service(
            web::resource("/test").to(|| HttpResponse::Ok().body("ok")),
    );
```

Shows it continuing to work as the middleware forces it on all routes outside of status:
```
curl 'http://127.0.0.1:3001/test' 
{"error":"Unauthorized"}

curl 'http://127.0.0.1:3001/test' --header "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJzdWIiOiItLS0tLUJFR0lOIFJTQSBQVUJMSUMgS0VZLS0tLS1cbk1JSUNDZ0tDQWdFQXMzMzNMRWQwYUozNEl6RnN0UFBKRHJnc21EV04zZUVXRTJKcThsMDFDRk1Wbk9WTDhTWmhcbnlYdzNqS3ljbU5iakM4aWhHSVJzNUlSVUVtVXhGVnFXbDgvb05Ed00xU1NOYjR3TmJBSVdTSTRJRDI3bTl1blBcbm9LRmduRFEzUndzOG9INlNnRzdHMFhZeWptTWFSVlV2M1Z2d2Z0d2JiWWpDbmxpcjdvYlN0ZGZ2dlNibnZhb21cbnBxcERzTGYrd2lhUFRxREYwUTFVTEZXM3ZiMjcvQVZmUkhVekNTUVlxbjdZWkFhRUVsOU9TUnZJS292a0RmOVJcbjBaM28xbndZcHlnTEF3NVYvNG1lVGRBcGN1UXV0TFNKK0pXZ0xvNmlERlpvbngvVDdpNHU3QkZIVDZaQ0VibzdcbjI3K20rVzVETjdiZzlJN3J5aEpxOTcvSnltVkUrS0luU3RZYkh6YVZ0ZFNkYzdxSURxWFpPcmMzMVlYZ0diTXpcbmozVkRIMFNIT3hDM21YSmh1bFVNeVFSRGx2R1BLdWR0RldJNEZkRVVJZ1E1Sm95VjRKZS9PS3VYVmphdlkrQXpcbkZIOVJLKy9KcU1CSGQ1b01xMzh2TDJzYTRtNTJSaEFOTk5ENWpQME1HNmh6TGlBOVF2QllSbm5FMlAxRnlRZ1FcbjB1R1BhdmJoZk13S1NWMTZjM2g4MXU4djhaQjU4TUNjcTMwSW9oRlBHWUNzZWJ5dS93VWg4cjAwckhzaWl6RFJcbmxoZFo1VWw2NFB6TTVTODlIc1FYbnJycTRsS3ZpM1J0M3VBTVlSQ25rOThKWUpBc0UrVlBLaU9MSDJvUWdzUHFcbnhid1B0OFJEMnhuWUxyT3pvR2JaSXQwUVpiZnNmdWs1aGpQZ2o3R1FrRG5TclJOdFBZVmRvb0VDQXdFQUFRPT1cbi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS1cbiIsImlzcyI6InRhcmkiLCJleHAiOjE1ODkzMjc2MzQsImlzc3VlZCI6MTU4ODk2NzYzNH0.JjbuXgqNkhK3awW9awAQ9Nsuzuj7rW49Yfn0GHBbRVQ9Ay6rNXS5D4F-SOwWt6_4SvicBPMHLd6jWVlZ7zwPj0IWGmziobISRHcOWlqgJ00NB2yfy7ug-PPr1tBZDbMJQ2qO4iZ03OUFXMO2X0mM__pqf9BifMIAX0ImwG_XAuow7iimN02pc_pjvkJn8fh-s7hORSDjBFYjwMSvE0rPJicnk7YDd95V9HE_UAHZZqOUIpEdd6rx88WcmSmXB0Wud5NXovod41LsjdQyC5k1BjgLiHbgsHmiFMdONnirR80KB78nYZHam1b164aGQHVJtTobnbvK-B84s-3DQ5jqSAgZgvOTA992fGKEWH56NCZ5ILgWAmUnL2iMYVlk065I8vM-z9od90e5qZpI-nfoUq_bBZ3wVonZMxI8nIdUJV4PE5bfpbpMR4hSTpI4DMjW8cYX8qfYcgzyLl4mBpqkRF8_wxb5pXTw-XyLUqkYLkdWI_OfxrgQNgiAChac4AUar-kOp1W7CaVnV_kK-b9dF7sRUvLu0HNA_oVJ6MPqr3hMuPJk4PVewXhE23UF9wrXny9zzFuC6_SB-x5UsBZntgpr1f7hk-wotTr3mswz6YpoZoIfDF-qsjkwW6ZS3rI8XAfmZ_YqeEJUJPbn-nLmjwZk2i8emEh_AQcHGeCUsq0"
ok

curl 'http://127.0.0.1:3001/status'
{"available":0,"max_size":32,"size":0}
```

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Feature refactor (No new feature or functional changes, but performance or technical debt improvements)
* [x] New Tests
* [ ] Documentation

## Checklist:

* [ ] I'm merging against the `development` branch.
* [x] I ran `cargo-fmt --all` before pushing.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.

2020-05-09 15:21 UTC, dunnock requested changes
Mostly good apart of few specific nits

2020-05-09 15:21 UTC, dunnock commented on node/src/api/errors/api_error.rs
> +                        status_code: StatusCode::UNPROCESSABLE_ENTITY,
```suggestion
                        status_code: StatusCode::INTERNAL_SERVER_ERROR,
```

2020-05-09 15:21 UTC, dunnock commented on node/src/api/middleware/authentication.rs
> +            Box::pin(async move { service.borrow_mut().call(request).await })
there is a trick here, you need to make sure that RefMut is dropped outside of the Future context, otherwise theremight be a panic (e.g. from another call to RefCell borrow_mut()):
```suggestion
            let fut = service.borrow_mut().call(request);
            Box::pin(async move { fut.await })
```

2020-05-09 15:21 UTC, dunnock commented on node/src/api/middleware/authentication.rs
> +                    Box::pin(async move { service.borrow_mut().call(request).await })
same as above

2020-05-11 13:11 UTC, Timo614 commented
Sounds good, should be set now. :+1:

2020-05-11 15:51 UTC, dunnock approved these changes
LGTM!

2020-05-11 17:30 UTC, merged